// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainSyncAPI.Data;

#nullable disable

namespace TrainSyncAPI.Migrations
{
    [DbContext(typeof(TrainSyncContext))]
    [Migration("20250709074101_IntermediaryTables")]
    partial class IntermediaryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainSyncAPI.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<string>("IntensityUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("RepsInReserve")
                        .HasColumnName("intensity_unit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Kilograms")
                        .HasColumnName("weight_unit");

                    b.HasKey("Id");

                    b.HasIndex("Title", "UserId")
                        .IsUnique();

                    b.ToTable("exercise");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("template");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.TemplateExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<double>("Order")
                        .HasColumnType("float")
                        .HasColumnName("order");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateId");

                    b.ToTable("template_exercise");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.TemplateExerciseSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("Intensity")
                        .HasColumnType("float")
                        .HasColumnName("intensity");

                    b.Property<string>("IntensityUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("RepsInReserve")
                        .HasColumnName("intensity_unit");

                    b.Property<double?>("Reps")
                        .HasColumnType("float")
                        .HasColumnName("reps");

                    b.Property<long>("TemplateExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_exercise_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Kilograms")
                        .HasColumnName("weight_unit");

                    b.HasKey("Id");

                    b.HasIndex("TemplateExerciseId");

                    b.ToTable("template_exercise_set");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<DateOnly>("ProgrammedDate")
                        .HasColumnType("date")
                        .HasColumnName("programmed_date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("workout");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.WorkoutExercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<double>("Order")
                        .HasColumnType("float")
                        .HasColumnName("order");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_exercise");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.WorkoutExerciseSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<double?>("Intensity")
                        .HasColumnType("float")
                        .HasColumnName("intensity");

                    b.Property<string>("IntensityUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("RepsInReserve")
                        .HasColumnName("intensity_unit");

                    b.Property<double?>("Reps")
                        .HasColumnType("float")
                        .HasColumnName("reps");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<double?>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Kilograms")
                        .HasColumnName("weight_unit");

                    b.Property<long>("WorkoutExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("workout_exercise_set");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.TemplateExercise", b =>
                {
                    b.HasOne("TrainSyncAPI.Models.Exercise", "Exercise")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainSyncAPI.Models.Template", "Template")
                        .WithMany("Exercises")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.TemplateExerciseSet", b =>
                {
                    b.HasOne("TrainSyncAPI.Models.TemplateExercise", "TemplateExercise")
                        .WithMany("Sets")
                        .HasForeignKey("TemplateExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateExercise");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.WorkoutExercise", b =>
                {
                    b.HasOne("TrainSyncAPI.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainSyncAPI.Models.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.WorkoutExerciseSet", b =>
                {
                    b.HasOne("TrainSyncAPI.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.Exercise", b =>
                {
                    b.Navigation("TemplateExercises");

                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.Template", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.TemplateExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TrainSyncAPI.Models.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
